name: Build & Deploy Remix Weather App

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'infra/tf-app/modules/remix-app/**'

  push:
    branches: [ main ]
    paths:
      - 'infra/tf-app/modules/remix-app/**'

jobs:
  docker-build:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Log in to ACR
        run: az acr login --name group7cst8918remixarc

      - name: Build and Push Docker image
        run: |
          docker build -t group7cst8918remixarc.azurecr.io/remix-weather:${{ github.sha }} infra/tf-app/modules/remix-app
          docker push group7cst8918remixarc.azurecr.io/remix-weather:${{ github.sha }}

  deploy-to-aks:
    if: github.event_name == 'push'
    needs: docker-build
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Run Terraform Apply
        run: |
          cd infra/tf-app
          terraform init
          terraform apply -auto-approve
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
