name: Build & Push Remix Weather App

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'infra/tf-app/modules/remix-app/**'

jobs:
  docker-build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Log in to ACR
        run: az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build and Push Docker image
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/remix-weather:${{ github.sha }} infra/tf-app/modules/remix-app
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/remix-weather:${{ github.sha }}
